### ISSUE TITLE
Error in stalling requirements

### ISSUE THREAD

**Issue by YHSot976** [rushilsrivastava/image-scrapers#1]
Could not find a version that satisfies the requirement urllib (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for urllib (from -r requirements.txt (line 3))

**Comment by rushilsrivastava** [comment]
`urllib` is a default Python Library. I must have forgotten to remove that from the requirements.txt. Remove that line from the requirements list, and rerun the pip install command.

**Comment by rushilsrivastava** [comment]
Should be fixed in https://github.com/rushilsrivastava/image-scrapers/commit/61a6e4cf99cd5a222cbd74ac1f8e515b6abc123e

**Comment by YHSot976** [comment]
Other modules also gave the same problem, only selenium, requests, argparse, pathlib, bs4 can be installed.

**Comment by rushilsrivastava** [comment]
Yeah, I just noticed I did not update the full list. `lxml` is not a default module on all distributions, so I have that included as well.

**Comment by rushilsrivastava** [comment]
Fixed: https://github.com/rushilsrivastava/image-scrapers/commit/25fd935696411b54372f57d80901914c99940ebd

**Comment by YHSot976** [comment]
I got the following. The chrome launched and all the pics loaded but not downloaded. Do you know where my problem is?

[%] Successfully launched Chrome Browser
[%] Successfully opened link.
[%] Scrolling down.
[%] Successfully clicked 'Show More Button'.
[%] Reached end of Page.
Traceback (most recent call last):
  File "google_scraper.py", line 120, in <module>
    source = search(url)
  File "google_scraper.py", line 55, in search
    f = open('dataset/logs/google/source.html', 'w+')
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/logs/google/source.html'

**Comment by YHSot976** [comment]
I guess the problem is when I run 
`python3.5 google-scraper.py "https://www.google.com/search?q=cats&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiwoLXK1qLVAhWqwFQKHYMwBs8Q_AUICigB" cats`
the cats argument gave an error of unrecognized arguments. So the folder cannot be created.
And when I run without the cats argument then I got the message like above.

**Comment by rushilsrivastava** [comment]
Hey, the new code I published doesn't require the second argument (keyword). You just need to give the link, and it will get the search query from the link. Try that, and if you still have an error, paste the stack trace on a new issue.
