### ISSUE TITLE
Is there a way to not return the JSON file for each image?

### ISSUE THREAD

**Issue by HappyAdjustableSpanners** [rushilsrivastava/image-scrapers#11]
I am returning lots of images and want to be able to simply copy and paste the folder of images by themselves after scraping them. I don't want to manually have to go and remove each json file. Is there a flag to stop the returning of the .json file for each image?

**Comment by rushilsrivastava** [comment]
Hi, the latest push will now no longer download image metadata by default. You can download image metadata with the `--json` argument.
