### ISSUE TITLE
Cannot create dataset folder

### ISSUE THREAD

**Issue by hendririberu** [rushilsrivastava/image-scrapers#12]
When i run the bing / google scrape. the folder dataset cannot be created. after finishing download, there is no dataset folder

**Comment by rushilsrivastava** [comment]
Do you have a console log/output that you could share?

**Comment by hendririberu** [comment]
hey, i just solved the problem, the python detected all folder named dataset, which i already had in root.

**Comment by rushilsrivastava** [comment]
Awesome. Glad you could figure it out.
