### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by albu5** [rushilsrivastava/image-scrapers#5]
Charmap encoding errors while dumping scraped data into 'dataset/logs/google/source.html'. Explicitly mentioning encoding while opening the file using open() might be useful.

**Comment by rushilsrivastava** [comment]
I think #6 will solve this issue. Awaiting @loopyd to make requested changes so I can merge.

**Comment by loopyd** [comment]
Worked on it, its evolving into a feature update, though, so I closed that PR.

**Comment by rushilsrivastava** [comment]
Patched with https://github.com/rushilsrivastava/image-scrapers/commit/9a07268a2e5191d788a981f817b78e0964adeefd
